FROM node:20-alpine
RUN apk add --no-cache tini
WORKDIR /app
ENV PORT=8090
COPY server.js ./

RUN addgroup -S appgroup \
    && adduser -S appuser -G appgroup
USER appuser
EXPOSE 8090

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "server.js"]
